# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  tf-plan:
    docker:
      - image: cimg/base:stable-20.04
    resource_class: medium
    environment:
      TF_VERSION: 1.0.11
    steps:
      - checkout
      - run:
          name: "Install tfswitch"
          command: |
            curl -L https://raw.githubusercontent.com/warrensbox/terraform-switcher/release/install.sh | bash
      - run:
          name: "Install Terraform ${TF_VERSION}"
          command: |
            tfswitch ${TF_VERSION}
      - run:
          name: "terraform plan"
          working_directory: terraform/dev
          command: |
            terraform init
            terraform validate
            terraform plan -out tfplan
  tf-apply:
    docker:
      - image: hashicorp/terraform:1.0.11
    resource_class: medium
    steps:
      - checkout
      - run: cd terraform/dev
      - run: terraform init
      - run: terraform apply -input=false -auto-approve tfplan

workflows:
  terraform-workflow:
    jobs:
      - tf-plan
      - tf-approval:
          type: approval
          requires:
            - tf-plan
          filters:
            branches:
              only: main
      - tf-apply:
          requires:
            - tf-approval
          filters:
            branches:
              only: main
      
