# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  tf-plan:
    docker:
      - image: hashicorp/terraform:1.0.11
    resource_class: medium
    steps:
      - checkout
      - run:
          name: "terraform plan"
          working_directory: terraform/dev
          command: |
            terraform init
            terraform validate
            terraform plan
  tf-apply:
    docker:
      - image: hashicorp/terraform:1.0.11
    resource_class: medium
    steps:
      - checkout
      - run:
          name: "terraform apply"
          working_directory: terraform/dev
          command: |
            terraform init

workflows:
  terraform-workflow:
    jobs:
      - tf-plan
      - tf-approval:
          type: approval
          requires:
            - tf-plan
          filters:
            branches:
              only: main
      - tf-apply:
          requires:
            - tf-approval
          filters:
            branches:
              only: main
      
