# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

commands:
  prepare-docker-environment:
    description: "To run before using Terraform docker provider."
    steps:
      - setup_remote_docker
      - run: 
          name: Instal Docker client
          command: apk add docker-cli

jobs:
  tf-plan:
    docker:
      - image: hashicorp/terraform:1.0.11
    resource_class: medium
    parameters:
      target-env:
        type: string
        default: dev
    steps:
      - checkout
      - prepare-docker-environment
      - run:
          name: "terraform plan"
          working_directory: terraform/<<parameters.target-env>>
          command: |
            terraform init
            terraform validate
            terraform plan -out tfplan
  tf-apply:
    docker:
      - image: hashicorp/terraform:1.0.11
    resource_class: medium
    parameters:
      target-env:
        type: string
        default: dev
    steps:
      - checkout
      - run:
          name: "terraform apply"
          working_directory: terraform/<<parameters.target-env>>
          command: |
            terraform init
            terraform apply -input=false -auto-approve tfplan

workflows:
  terraform-workflow:
    jobs:
      - tf-plan:
          name: tf-plan-<<matrix.target-env>>
          matrix:
            parameters:
              target-env: ["dev", "prod"]
      - tf-approval:
          type: approval
          name: tf-approval-<<matrix.target-env>>
          matrix:
            parameters:
              target-env: ["dev", "prod"]
          requires:
            - tf-plan-<<matrix.target-env>>
      - tf-apply:
          name: tf-apply-<<matrix.target-env>>
          matrix:
            parameters:
              target-env: ["dev", "prod"]
          requires:
            - tf-approval-<<matrix.target-env>>
